CREATE TABLE CELULARES_XIIF(
  ID NUMBER PRIMARY KEY,
  MARCA NVARCHAR2(50),
  MODELO NVARCHAR2(50),
  COLOR NUMBER,  --- 1 BLANCO 2 ROJO  3 NEGRO 4 AZUL 5 NO EXISTE COLOR 
  COMPANIA NVARCHAR2(50),
  PRECIO NUMBER
);

-- EUDEZ 2 -  7  LORENZO 8-13 CONSTANTINO 14-19
INSERT INTO CELULARES_XIIF VALUES(1,'SAMSUM','A 50',1,'TELCEL',5000);
INSERT INTO CELULARES_XIIF VALUES(2, 'ZTE','10A',3,'BYTE',4000);
INSERT INTO CELULARES_XIIF VALUES(3, 'LG','XT',2,'TYT',2000);
INSERT INTO CELULARES_XIIF VALUES(4, 'HUAWEI','XTE',1,'MOVISTAR',3000);
INSERT INTO CELULARES_XIIF VALUES(5, 'SAMSUNG','A10',2,'BYTE',4500);
INSERT INTO CELULARES_XIIF VALUES(6, 'NOKIA','11Z',4,'MOVISTAR',1590);
INSERT INTO CELULARES_XIIF VALUES(7, 'IPHONE','11',1,'TELCEL',25000);
INSERT INTO CELULARES_XIIF VALUES(8,'MOTOROLA','A50',2,'TELCEL',2500);
INSERT INTO CELULARES_XIIF VALUES(9,'OPPO','A53',3,'MOVISTAR',3500);
INSERT INTO CELULARES_XIIF VALUES(10,'LG','K20',2,'TELCEL',500);
INSERT INTO CELULARES_XIIF VALUES(11,'MOTOROLA','G6',1,'TELCEL',1500);
INSERT INTO CELULARES_XIIF VALUES(12,'LANIX','A8',3,'TELCEL',500);
INSERT INTO CELULARES_XIIF VALUES(13,'HISSEN','A20',3,'MOVISTAR',2500);
INSERT INTO CELULARES_XIIF VALUES(14,'NOKIA','LUMIA',3,'TELCEL',8000);
INSERT INTO CELULARES_XIIF VALUES(15,'MOTOROLA','G8',1,'MOVISTAR',4000);
INSERT INTO CELULARES_XIIF VALUES(16,'MOTOROLA','G8 PLUS',1,'TELCEL',6000);
INSERT INTO CELULARES_XIIF VALUES(17,'XIAOMI','POCO X4 PRO',4,'TELCEL',8000);
INSERT INTO CELULARES_XIIF VALUES(18,'ASUS','ROK PHONE',2,'LIBERADO',25000);
INSERT INTO CELULARES_XIIF VALUES(19,'XIAOMI','BLACK SHARCK',3,'TELCEL',25000);
SELECT * FROM CELULARES_XIIF;

-- CASE --> IF  --- 1 BLANCO 2 ROJO  3 NEGRO 4 AZUL 5 NO EXISTE COLOR 
SELECT ID,MARCA,MODELO,COLOR,
( CASE COLOR 
WHEN 1 THEN 'BLANCO'
WHEN 2 THEN 'ROJO'
WHEN 3 THEN 'NEGRO'
WHEN 4 THEN 'AZUL'
ELSE 'NO EXSISTE COLOR'
END 
) AS DETALLE_COLOR, COMPANIA, PRECIO
FROM CELULARES_XIIF WHERE PRECIO > 5000;

SELECT ID,MARCA,MODELO,COLOR, COMPANIA, PRECIO,
( CASE 
WHEN PRECIO <= 5000  THEN 'PRECIO BARATO'
WHEN PRECIO  > 5000 AND PRECIO  < 8000 THEN 'PRECIO REGULAR'
WHEN PRECIO > 8000 THEN 'PRECIO CARO'
ELSE 'SOLOR POR PEDIDO' END 
) AS DETALLE_PRECIO FROM CELULARES_XIIF;

--- CONTAR CUANTOS CELULARES TENGO POR MARCA CON CASE 
SELECT Modelo, COUNT(ID)CONTADOR
FROM  CELULARES_XIIF
GROUP BY MODELO;



-- SUMAR LOS CELULARES DE LA MARCA SAMSUM 
SELECT COUNT(ID) CONTADOR FROM CELULARES_XIIF WHERE MARCA = 'SAMSUNG';

-- SaCAR EL PROMEDIO DE LOS CELUALRES DE LA COMPANIA TELCEL 

-- MOSTRAR EL CELULAR MAS CARO 
SELECT MAX(PRECIO)MAX_PRECIO FROM CELULARES_XIIF;
SELECT * FROM CELULARES_XIIF;

--- CONTAR CUANTOS CELUALRES TENGO CON PRECIO REGULAR 


--MOSTRAR LOS CELULARES MOVITAR SY SACAR EL MAS ECONOMICO 

--- AGRUPAR LOS CELULARES POR MARCA 

SELECT MARCA, COUNT(ID)CONTADOR
FROM CELULARES_XIIF
GROUP BY MARCA;

-- SACAR EL PROMEDIO DE LOS CELULARES MAS ECONMICOS 

-- CONTAR CUANTOS CELUALRES TENGO MAS CAROS

Micro srvios
---------------------------------------------

CREATE TABLE CLIENTES_XIIF(
ID NUMBER PRIMARY KEY NOT NULL,
NOMBRE NVARCHAR2(100),
APP NVARCHAR2(100),
APM NVARCHAR2(100),
TELEFONO NUMBER,
CORREO NVARCHAR2(100),
ESTATUS NUMBER  ---1 ESTAUS ACTIVO 2 INACTIVO 3 BURO
);

INSERT INTO CLIENTES_XIIF VALUES(1,'LORENZO','JUAREZ','CARRANZA',2221234567,'lorenzo@gmail.com',1);
SELECT * FROM CLIENTES_XIIF;
DROP TABLE CLIENTES_XIIF;
commit;

delete from  CLIENTES_XIIF whewe id=?;

--recueprar registros
select * from CLIENTES_XIIF whewe id=;







