--Funciones

CREATE TABLE REFRESCO_M(
ID_REFRESCO NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(100),
MARCA  NVARCHAR2(100),
PRECIO NUMBER,
CONTENIDO NUMBER
);

DROP TABLE REFRESCO_M;

--INFORMACION PARA RELLENAR

INSERT INTO REFRESCO_M VALUES(1,'MANZANITA SOL','PEPSI',20, 160);
INSERT INTO REFRESCO_M VALUES(2,'MANZANITA LIFT','COCA COLA',25, 180);
INSERT INTO REFRESCO_M VALUES(3,'MIRINDA','PEPSI',20, 130);
INSERT INTO REFRESCO_M VALUES(4,'FANTA','COCA COLA',30, 200);
INSERT INTO REFRESCO_M VALUES(5,'BIG COLA','BIG COLA',20, 2000);
INSERT INTO REFRESCO_M VALUES(6,'SPRINT','COCA COLA ',35, 3000);

SELECT * FROM REFRESCO_M;

----COUT CONTADOR
SELECT COUNT(ID_REFRESCO) CONTADOR FROM REFRESCO_M WHERE MARCA = 'COCA COLA';
SELECT COUNT(ID_REFRESCO) CONTADOR FROM REFRESCO_M WHERE MARCA = 'PEPSI';

select count (id_refresco)contador from refresco_m where marca= 'Coca cola';
select count (id_refresco)contador from refresco_m where marca= 'Pepsi';

--SUM

SELECT SUM(PRECIO)AS PRECIO_SUM FROM REFRESCO_M WHERE MARCA = 'COCA COLA';

--OBTENER EL CONTENIDO MAS ALTO

SELECT MAX(CONTENIDO)MAX_CONTENIDO FROM REFRESCO_M;

--OBTENER EL CONTENIDO MINIMO

SELECT MIN(CONTENIDO)MIN_CONTENIDO FROM REFRESCO_M;

select MIN(CONTENIDO)MIN_CONTENIDO from REFRESCO_M;

--OBTENER EL PROMEDIO DE PRECIO DELOS REFRESCOS QUE EMPIECEN CON M

SELECT AVG(PRECIO)PROMEDIO_PRECIO FROM REFRESCO_M WHERE NOMBRE LIKE 'M%';

SELECT AVG(PRECIO) PROMEDIO_PRECIO FROM REFRESCO_M WHERE NOMBRE LIKE'%M%';

--MOSTRAR LOS NOMBRES EN MAYUSCULAS

SELECT ID_REFRESCO, UPPER(NOMBRE)NOMBRE, PRECIO, CONTENIDO FROM REFRESCO_M;

SELECT ID_REFRESCO, UPPER(NOMBRE)NOMBRE, MARCA, PRECIO, CONTENIDO FROM REFRESCO_M;

--MOSTRAR LOS NOMBRES EN MINUSCULAS
SELECT ID_REFRESCO, LOWER(NOMBRE)NOMBRE, PRECIO, CONTENIDO FROM REFRESCO_M;

SELECT ID_REFRESCO, LOWER(NOMBRE)NOMBRE, MARCA, PRECIO, CONTENIDO FROM REFRESCO_M;

--MOSTRAR LAS MARCAS SIN REPETIR

SELECT DISTINCT(MARCA) FROM REFRESCO_M;

SELECT DISTINCT(MARCA)FROM REFRESCO_M;


--MOSTRA CUANTOS REFRESCOS TENGO EN UNA MARCA

SELECT MARCA, COUNT(ID_REFRESCO)CONTADOR
FROM REFRESCO_M
GROUP BY MARCA;


--CONCATENAR EL PRECIO EL SIG

SELECT CONCAT('$',PRECIO)AS RESULT, NOMBRE FROM
REFRESCO_M;

SELECT CONCAT('$',PRECIO)AS RESULT FROM
REFRESCO_M;


SELECT ID_REFRESCO, NOMBRE, CONCAT('$',PRECIO)FROM
REFRESCO_M;

--ACTIIDAD

CREATE TABLE CELULAR_M(
ID_CELULAR NUMBER PRIMARY KEY,
MODELO NVARCHAR2(100),
MARCA NVARCHAR2(100),
PRECIO NUMBER,
CAPACIDAD NUMBER
);

DROP TABLE CELULAR_M;
--1.- AGREGAR 7 INSERT DE CUALQUIER CELULAR


INSERT INTO CELULAR_M VALUES(1,'MOTO G22','MOTOROLA',5820,124);
INSERT INTO CELULAR_M VALUES(2,'RENO 7','OPPO',9000,124);
INSERT INTO CELULAR_M VALUES(3,'NOTE 6 PRO','REDMI',7000,32);
INSERT INTO CELULAR_M VALUES(4,'GALAXY A22','SAMSUNG',6000,128);
INSERT INTO CELULAR_M VALUES(5,'X7','XONOR',5800,128);
INSERT INTO CELULAR_M VALUES(6,'GALAXY A32','SAMSUNG',6000,64);
INSERT INTO CELULAR_M VALUES(7,'iPHONE 11','APPLE',12000,256);


SELECT * FROM CELULAR_M;

--2.- CONTAR CUANTOS TELEFONOS TENGO DE LA MARCA SANSUNG

SELECT COUNT(ID_CELULAR) CONTADOR FROM CELULAR_M WHERE MARCA = 'SAMSUNG';

--3.- OBTENER EL PRECIO MAS CARO DE LOS TELEFONOS

SELECT MAX(PRECIO)MAX_PRECIO FROM CELULAR_M;

--4.-OBTENER LA CAPACIDAD MAS BAJA DE LOS TELEFONOS

SELECT MIN(CAPACIDAD)MIN_CAPACIDAD FROM CELULAR_M;

--5-. SUMAR LOS PRECIO DE LOS TELEFONOS DE LA MARCA SANSUNG

SELECT SUM(PRECIO)AS PRECIO_SUM FROM CELULAR_M WHERE MARCA = 'SAMSUNG';

--6.- OBTENER LA MEDIA DE LOS CELULARES QUE SU NOMBRE TENGA UNA G


SELECT AVG(PRECIO)PROMEDIO_PRECIO FROM CELULAR_M WHERE MARCA LIKE 'G%';



--7.- CAMBIAR LA MARC DEL ID 3 POR EL DEL LG

UPDATE CELULAR_M SET MARCA = 'LG' where ID_CELULAR = 3;
SELECT * FROM CELULAR_M;


--8.- MOSTRAR LOS TELEFONOS ORDENADOS EN BASE A SU PRECIO Y ELNOMBRE PONERLO EN MAYUSCULAS Y EL PRECIO CONTATENARLO EN EL SIGNO DE $

SELECT UPPER(MARCA)MARCA,CONCAT('$',PRECIO)MARCA FROM CELULAR_M ORDER BY PRECIO ASC;

--9.- CONTAR CUANTOS TELEFONOS TENGO DE CADA MARCA

SELECT MARCA, COUNT(ID_CELULAR)CONTADOR
FROM CELULAR_M
GROUP BY MARCA;

--10.- MOSTRAR LOS PRECIOS DEL ID 6, 2 ,4

SELECT * FROM CELULAR_M WHERE PRECIO IN(6,2,4);


